name: DevSecOps-Advanced-Pipeline

on:
  push:
    branches: [ "master", "main" ]

permissions:
  security-events: write
  contents: read

jobs:
  security-scans:
    name: Advanced Security Suite
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Gitleaks (Secrets)
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
      
      - name: Run Trivy (SCA)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'image'
          image-ref: 'bkimminich/juice-shop:latest'
          severity: 'HIGH,CRITICAL'
          format: 'github'
          output: 'trivy-report.md'
        continue-on-error: true

      - name: Publish Trivy Report to Job Summary
        run: |
          if [ -s trivy-report.md ]; then
            cat trivy-report.md >> $GITHUB_STEP_SUMMARY
          else
            echo "### 📦 Trivy Container Scan: No high/critical vulnerabilities found!" >> $GITHUB_STEP_SUMMARY
          fi
        if: always()
      
      - name: Run Semgrep (SAST)
        run: |
          pip install semgrep
          semgrep scan --config auto --sarif --output semgrep-results.sarif
        continue-on-error: true

      - name: Upload Semgrep Results to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep-results.sarif
        if: always() # Этот шаг выполнится в любом случае
