name: DevSecOps-Advanced-Pipeline

on:
  push:
    branches: [ "master", "main" ]

jobs:
  security-scans:
    name: Advanced Security Suite
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Просто скачиваем файлы проекта из репозитория
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Шаг 2: Поиск секретов (Gitleaks)
      - name: Run Gitleaks (Secrets)
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      # Шаг 3: Проверка библиотек (Trivy). Он сам найдет файл package.json и проверит его
      - name: Run Trivy (SCA)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'
          severity: 'HIGH,CRITICAL'
        continue-on-error: true

      # Шаг 4: Сканирование самого кода на уязвимости (Semgrep)
      - name: Run Semgrep (SAST)
        run: |
          pip install semgrep
          semgrep scan --config auto
        continue-on-error: true
